/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Artifacts": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "BuildOrchestrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "BuildQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "BuildQueueDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Deployments": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DeploymentsHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "EnvVarsHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ImageFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Logs": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "LogsHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Projects": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ServerFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebhookApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "WebhookHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}