/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Artifacts": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Deployments": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Logs": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Projects": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}